### ISSUE TITLE
[Usage] This image does not exist, please check

### ISSUE THREAD

**Issue by yongxinwang-ai** [FudanDISC/ReForm-Eval#2]
Thanks for your good work! I believe the work will make a great contribution to the community.

And my question is, the images are in the format of base64, why the images don't exist in designated path when I use hf?

Should I load the original images and modify the configs?

**Comment by Aweminus** [comment]
You can try to download our **Reform-Eval Data** to the root directory through the provided link, and then use `--offline_hf`, please refer to the Load Data section in Readme.md
