### ISSUE TITLE
Discrepancy between the paper and listed benchmarks in the repo

### ISSUE THREAD

**Issue by zhimin-z** [FudanDISC/ReForm-Eval#8]
![image](https://github.com/FudanDISC/ReForm-Eval/assets/8592144/fb046840-2dce-45b2-bf64-e2ee4feacecb)
![image](https://github.com/FudanDISC/ReForm-Eval/assets/8592144/3b716fef-5de1-49a7-bf42-dbbbccde6add)
Flowers102 is not found in the paper...

**Comment by IMNearth** [comment]
Hi zhimin, 
Actually we have included Flowers102 in the paper. 

The table you listed is Table 6 in Page 18 about the statistics of datasets on visual cognition tasks. However, Flowers102 is a dataset that used to evaluate the coarse-grained perception ability of models. Thus, this dataset is included in Table 5, Page 17. You just have to scroll up to find the information.

Just for your convenience, I cropped the table here.
<img width="751" alt="截屏2024-01-25 16 21 21" src="https://github.com/FudanDISC/ReForm-Eval/assets/44335569/d5abfb48-f3dd-41f0-b729-d6a8045c14f6">
